### ISSUE TITLE
npm run dev not work

### ISSUE THREAD

**Issue by XabierGoenaga** [Pondorasti/nextjs-chrome-extension#1]
Hi there.

I have had this problem after having searched in forums I have not found a solution but to try I have changed the command from gsed to sed and it worked.

![Captura](https://user-images.githubusercontent.com/53001332/171733669-39d2da49-9430-4a20-9c8b-fa1992177bea.PNG)

And now work!
```
"scripts": {
    "dev": "npm-watch",
    "build": "next build && next export && npm run lint:build",
    "lint:build": "mv out/_next out/assets && sed -i 's/\\/_next/\\/assets/g' out/**.html",
    "lint": "next lint"
  },
```

**Comment by pondorasti** [comment]
Thanks for taking the time to open this issue. The template uses `gnu-sed` (`gsed`) to bundle the project into a chrome extension. As far as I'm aware there's a couple distributions between stream editors and depends how you have it aliased on your machine.

I've took this opportunity to clarify the `README` and add `gsed` instructions.
